// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerPronaunceDemo.Context;

#nullable disable

namespace PlayerPronaunceDemo.Migrations
{
    [DbContext(typeof(PPContext))]
    [Migration("20251023140455_mig_add_sound")]
    partial class mig_add_sound
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayerPronaunceDemo.Entities.FootbalPlayer", b =>
                {
                    b.Property<int>("FootbalPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FootbalPlayerId"));

                    b.Property<int>("FootballTeamId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationFlagImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FootbalPlayerId");

                    b.HasIndex("FootballTeamId");

                    b.ToTable("FootbalPlayers");
                });

            modelBuilder.Entity("PlayerPronaunceDemo.Entities.FootballTeam", b =>
                {
                    b.Property<int>("FootballTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FootballTeamId"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FootballTeamId");

                    b.ToTable("FootballTeams");
                });

            modelBuilder.Entity("PlayerPronaunceDemo.Entities.Sound", b =>
                {
                    b.Property<int>("SoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoundId"));

                    b.Property<int>("FootballPlayerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEpic")
                        .HasColumnType("bit");

                    b.Property<string>("SoundNation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoundPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SoundId");

                    b.HasIndex("FootballPlayerId");

                    b.ToTable("Sounds");
                });

            modelBuilder.Entity("PlayerPronaunceDemo.Entities.FootbalPlayer", b =>
                {
                    b.HasOne("PlayerPronaunceDemo.Entities.FootballTeam", "footballTeam")
                        .WithMany("Players")
                        .HasForeignKey("FootballTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("footballTeam");
                });

            modelBuilder.Entity("PlayerPronaunceDemo.Entities.Sound", b =>
                {
                    b.HasOne("PlayerPronaunceDemo.Entities.FootbalPlayer", "footballPlayer")
                        .WithMany("Sounds")
                        .HasForeignKey("FootballPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("footballPlayer");
                });

            modelBuilder.Entity("PlayerPronaunceDemo.Entities.FootbalPlayer", b =>
                {
                    b.Navigation("Sounds");
                });

            modelBuilder.Entity("PlayerPronaunceDemo.Entities.FootballTeam", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
